const locationsDefaults = {
      g1: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      g2: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      g3: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      // north door
      g4: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      g5: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      g6: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      g7: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      f1: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      f2: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      f3: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      f4: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      f5: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      f6: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      f7: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      e1: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      e2: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      e3: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      e4: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      e5: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      e6: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      e7: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      // west door
      d1: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      d2: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      d3: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      d4: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      d5: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      d6: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      // east door
      d7: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      c1: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      c2: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      c3: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      c4: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      c5: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      c6: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      c7: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      b1: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      b2: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      b3: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      b4: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      b5: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      b6: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      b7: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      a1: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      a2: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      a3: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      // south door
      a4: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      a5: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      a6: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
      a7: {
            areaExit: null,
            areaEffect: null,
            element: null,
            floorStyle: null,
            groundItem: null,
      },
};

export default locationsDefaults;
