export * from "./ispeech";
export * from "./istate-data";
export * from "./igame-state-data";
export * from "./iarea-state-data";
export * from "./iplayer-state-data";
export * from "./idialogue-state-data";
export * from "./iinventory-state-data";
export * from "./iinventory-item";
export * from "./iitem-properties";
