import { MonsterClass, Direction, ElementClass, CharacterState, ObjectType } from "../../game/shared/enums";
import { IAreaElement } from "../../game/area/interfaces";
import { armour, weapons, keyItems, potions } from "../items";
import { IWeapons } from "../../game/item/interfaces";

export default {
      room: 16,
      areaLoadMessage: "Room 16",
      areaElements: [
            {
                  type: ElementClass.player,
                  elementProperties: {
                        name: "Smelly Jeremy",
                        imageFileName: "player1.jpg",
                  },
                  startingPositionX: 4,
                  startingPositionY: "a",
                  startingDirection: Direction.N,
                  direction: Direction.N,
            },
            {
                  type: ElementClass.npc,
                  elementProperties: {
                        id: "28be7086-bafe-49f5-9e3c-ec3ca90e45a6",
                        asleep: true,
                        angry: false,
                        level: 1,
                        maxHp: 50,
                        lowHealthThreshold: 6,
                        maxPauseDuration: 1,
                        name: "Test",
                        class: MonsterClass.Human,
                        startingDirection: Direction.S,
                        direction: Direction.S,
                        patrolArea: true,
                        directionsForPatrol: [
                        ],
                        startingTargetLocation: "c7",
                        maxHuntingDuration: 3,
                        startingState: CharacterState.walkingPath,
                        speechResponse: "I'm gonna kill you",
                        sleepResponse: "Zzzzzzzzzzzzzzzz",
                        lootParameters: {
                              level: 6,
                              allowWeapon: true,
                              allowPotion: false,
                              allowKey: false,
                        },
                        armour: {
                              head: armour.leatherHelmet,
                              arms: null,
                              hands: null,
                              torso: armour.leatherChestPiece,
                              legs: null,
                              boots: armour.leatherBoots,
                        },
                        weapons: {
                              primary: weapons.axe,
                              secondary: null,
                              concealed: null,
                              shield: null,
                        } as IWeapons,
                        loot: [
                              potions.largeHealthBuff,
                              potions.smallDamageBuff,
                        ],
                        imageFileName: "",
                        startingLocation: "g1",
                  },
                  startingPositionY: "g",
                  startingPositionX: 1,
            },
            {
                  type: ElementClass.npc,
                  elementProperties: {
                        id: "28be7086-bafe-49f5-9e3c-ec3ca90e45a6",
                        asleep: true,
                        angry: false,
                        level: 1,
                        maxHp: 50,
                        lowHealthThreshold: 6,
                        maxPauseDuration: 1,
                        name: "Test",
                        class: MonsterClass.Human,
                        startingDirection: Direction.S,
                        direction: Direction.S,
                        patrolArea: true,
                        directionsForPatrol: [
                        ],
                        startingTargetLocation: "c6",
                        maxHuntingDuration: 3,
                        startingState: CharacterState.walkingPath,
                        speechResponse: "I'm gonna kill you",
                        sleepResponse: "Zzzzzzzzzzzzzzzz",
                        lootParameters: {
                              level: 6,
                              allowWeapon: true,
                              allowPotion: false,
                              allowKey: false,
                        },
                        armour: {
                              head: armour.leatherHelmet,
                              arms: null,
                              hands: null,
                              torso: armour.leatherChestPiece,
                              legs: null,
                              boots: armour.leatherBoots,
                        },
                        weapons: {
                              primary: weapons.axe,
                              secondary: null,
                              concealed: null,
                              shield: null,
                        } as IWeapons,
                        loot: [
                              potions.largeHealthBuff,
                              potions.smallDamageBuff,
                        ],
                        imageFileName: "",
                        startingLocation: "g2",
                  },
                  startingPositionY: "g",
                  startingPositionX: 2,
            },
            // {
            //       type: ElementClass.npc,
            //       elementProperties: {
            //             id: "28be7086-bafe-49f5-9e3c-ec3ca90e45a6",
            //             asleep: true,
            //             angry: false,
            //             level: 1,
            //             maxHp: 50,
            //             lowHealthThreshold: 6,
            //             maxPauseDuration: 1,
            //             name: "Test",
            //             class: MonsterClass.Human,
            //             startingDirection: Direction.S,
            //             direction: Direction.S,
            //             patrolArea: true,
            //             directionsForPatrol: [
            //             ],
            //             startingTargetLocation: "c5",
            //             maxHuntingDuration: 3,
            //             startingState: CharacterState.walkingPath,
            //             speechResponse: "I'm gonna kill you",
            //             sleepResponse: "Zzzzzzzzzzzzzzzz",
            //             lootParameters: {
            //                   level: 6,
            //                   allowWeapon: true,
            //                   allowPotion: false,
            //                   allowKey: false,
            //             },
            //             armour: {
            //                   head: armour.leatherHelmet,
            //                   arms: null,
            //                   hands: null,
            //                   torso: armour.leatherChestPiece,
            //                   legs: null,
            //                   boots: armour.leatherBoots,
            //             },
            //             weapons: {
            //                   primary: weapons.axe,
            //                   secondary: null,
            //                   concealed: null,
            //                   shield: null,
            //             } as IWeapons,
            //             loot: [
            //                   potions.largeHealthBuff,
            //                   potions.smallDamageBuff,
            //             ],
            //             imageFileName: "",
            //             startingLocation: "g3",
            //       },
            //       startingPositionY: "g",
            //       startingPositionX: 3,
            // },
            {
                  type: ElementClass.npc,
                  elementProperties: {
                        id: "28be7086-bafe-49f5-9e3c-ec3ca90e45a6",
                        asleep: true,
                        angry: false,
                        level: 1,
                        maxHp: 50,
                        lowHealthThreshold: 6,
                        maxPauseDuration: 1,
                        name: "Test",
                        class: MonsterClass.Human,
                        startingDirection: Direction.S,
                        direction: Direction.S,
                        patrolArea: true,
                        directionsForPatrol: [
                        ],
                        startingTargetLocation: "c4",
                        maxHuntingDuration: 3,
                        startingState: CharacterState.walkingPath,
                        speechResponse: "I'm gonna kill you",
                        sleepResponse: "Zzzzzzzzzzzzzzzz",
                        lootParameters: {
                              level: 6,
                              allowWeapon: true,
                              allowPotion: false,
                              allowKey: false,
                        },
                        armour: {
                              head: armour.leatherHelmet,
                              arms: null,
                              hands: null,
                              torso: armour.leatherChestPiece,
                              legs: null,
                              boots: armour.leatherBoots,
                        },
                        weapons: {
                              primary: weapons.axe,
                              secondary: null,
                              concealed: null,
                              shield: null,
                        } as IWeapons,
                        loot: [
                              potions.largeHealthBuff,
                              potions.smallDamageBuff,
                        ],
                        imageFileName: "",
                        startingLocation: "g4",
                  },
                  startingPositionY: "g",
                  startingPositionX: 4,
            },
            // {
            //       type: ElementClass.npc,
            //       elementProperties: {
            //             id: "28be7086-bafe-49f5-9e3c-ec3ca90e45a6",
            //             asleep: true,
            //             angry: false,
            //             level: 1,
            //             maxHp: 50,
            //             lowHealthThreshold: 6,
            //             maxPauseDuration: 1,
            //             name: "Test",
            //             class: MonsterClass.Human,
            //             startingDirection: Direction.S,
            //             direction: Direction.S,
            //             patrolArea: true,
            //             directionsForPatrol: [
            //             ],
            //             startingTargetLocation: "c3",
            //             maxHuntingDuration: 3,
            //             startingState: CharacterState.walkingPath,
            //             speechResponse: "I'm gonna kill you",
            //             sleepResponse: "Zzzzzzzzzzzzzzzz",
            //             lootParameters: {
            //                   level: 6,
            //                   allowWeapon: true,
            //                   allowPotion: false,
            //                   allowKey: false,
            //             },
            //             armour: {
            //                   head: armour.leatherHelmet,
            //                   arms: null,
            //                   hands: null,
            //                   torso: armour.leatherChestPiece,
            //                   legs: null,
            //                   boots: armour.leatherBoots,
            //             },
            //             weapons: {
            //                   primary: weapons.axe,
            //                   secondary: null,
            //                   concealed: null,
            //                   shield: null,
            //             } as IWeapons,
            //             loot: [
            //                   potions.largeHealthBuff,
            //                   potions.smallDamageBuff,
            //             ],
            //             imageFileName: "",
            //             startingLocation: "g5",
            //       },
            //       startingPositionY: "g",
            //       startingPositionX: 5,
            // },
            {
                  type: ElementClass.npc,
                  elementProperties: {
                        id: "28be7086-bafe-49f5-9e3c-ec3ca90e45a6",
                        asleep: true,
                        angry: false,
                        level: 1,
                        maxHp: 50,
                        lowHealthThreshold: 6,
                        maxPauseDuration: 1,
                        name: "Test",
                        class: MonsterClass.Human,
                        startingDirection: Direction.S,
                        direction: Direction.S,
                        patrolArea: true,
                        directionsForPatrol: [
                        ],
                        startingTargetLocation: "c2",
                        maxHuntingDuration: 3,
                        startingState: CharacterState.walkingPath,
                        speechResponse: "I'm gonna kill you",
                        sleepResponse: "Zzzzzzzzzzzzzzzz",
                        lootParameters: {
                              level: 6,
                              allowWeapon: true,
                              allowPotion: false,
                              allowKey: false,
                        },
                        armour: {
                              head: armour.leatherHelmet,
                              arms: null,
                              hands: null,
                              torso: armour.leatherChestPiece,
                              legs: null,
                              boots: armour.leatherBoots,
                        },
                        weapons: {
                              primary: weapons.axe,
                              secondary: null,
                              concealed: null,
                              shield: null,
                        } as IWeapons,
                        loot: [
                              potions.largeHealthBuff,
                              potions.smallDamageBuff,
                        ],
                        imageFileName: "",
                        startingLocation: "g6",
                  },
                  startingPositionY: "g",
                  startingPositionX: 6,
            },
            {
                  type: ElementClass.npc,
                  elementProperties: {
                        id: "28be7086-bafe-49f5-9e3c-ec3ca90e45a6",
                        asleep: true,
                        angry: false,
                        level: 1,
                        maxHp: 50,
                        lowHealthThreshold: 6,
                        maxPauseDuration: 1,
                        name: "Test",
                        class: MonsterClass.Human,
                        startingDirection: Direction.S,
                        direction: Direction.S,
                        patrolArea: true,
                        directionsForPatrol: [
                        ],
                        startingTargetLocation: "c1",
                        maxHuntingDuration: 3,
                        startingState: CharacterState.walkingPath,
                        speechResponse: "I'm gonna kill you",
                        sleepResponse: "Zzzzzzzzzzzzzzzz",
                        lootParameters: {
                              level: 6,
                              allowWeapon: true,
                              allowPotion: false,
                              allowKey: false,
                        },
                        armour: {
                              head: armour.leatherHelmet,
                              arms: null,
                              hands: null,
                              torso: armour.leatherChestPiece,
                              legs: null,
                              boots: armour.leatherBoots,
                        },
                        weapons: {
                              primary: weapons.axe,
                              secondary: null,
                              concealed: null,
                              shield: null,
                        } as IWeapons,
                        loot: [
                              potions.largeHealthBuff,
                              potions.smallDamageBuff,
                        ],
                        imageFileName: "",
                        startingLocation: "g7",
                  },
                  startingPositionY: "g",
                  startingPositionX: 7,
            },
            {
                  type: ElementClass.enemy,
                  elementProperties: {
                        id: "28be7086-bafe-49f5-9e3c-ec3ca90e45a6",
                        asleep: true,
                        angry: false,
                        level: 1,
                        maxHp: 50,
                        lowHealthThreshold: 6,
                        maxPauseDuration: 1,
                        name: "Test",
                        class: MonsterClass.Human,
                        startingDirection: Direction.S,
                        direction: Direction.S,
                        patrolArea: true,
                        directionsForPatrol: [
                        ],
                        startingTargetLocation: "g7",
                        maxHuntingDuration: 3,
                        startingState: CharacterState.walkingPath,
                        speechResponse: "I'm gonna kill you",
                        sleepResponse: "Zzzzzzzzzzzzzzzz",
                        lootParameters: {
                              level: 6,
                              allowWeapon: true,
                              allowPotion: false,
                              allowKey: false,
                        },
                        armour: {
                              head: armour.leatherHelmet,
                              arms: null,
                              hands: null,
                              torso: armour.leatherChestPiece,
                              legs: null,
                              boots: armour.leatherBoots,
                        },
                        weapons: {
                              primary: weapons.axe,
                              secondary: null,
                              concealed: null,
                              shield: null,
                        } as IWeapons,
                        loot: [
                              potions.largeHealthBuff,
                              potions.smallDamageBuff,
                        ],
                        imageFileName: "",
                        startingLocation: "c1",
                  },
                  startingPositionY: "c",
                  startingPositionX: 1,
            },
            // {
            //       type: ElementClass.enemy,
            //       elementProperties: {
            //             id: "28be7086-bafe-49f5-9e3c-ec3ca90e45a6",
            //             asleep: true,
            //             angry: false,
            //             level: 1,
            //             maxHp: 50,
            //             lowHealthThreshold: 6,
            //             maxPauseDuration: 1,
            //             name: "Test",
            //             class: MonsterClass.Human,
            //             startingDirection: Direction.S,
            //             direction: Direction.S,
            //             patrolArea: true,
            //             directionsForPatrol: [
            //             ],
            //             startingTargetLocation: "g6",
            //             maxHuntingDuration: 3,
            //             startingState: CharacterState.walkingPath,
            //             speechResponse: "I'm gonna kill you",
            //             sleepResponse: "Zzzzzzzzzzzzzzzz",
            //             lootParameters: {
            //                   level: 6,
            //                   allowWeapon: true,
            //                   allowPotion: false,
            //                   allowKey: false,
            //             },
            //             armour: {
            //                   head: armour.leatherHelmet,
            //                   arms: null,
            //                   hands: null,
            //                   torso: armour.leatherChestPiece,
            //                   legs: null,
            //                   boots: armour.leatherBoots,
            //             },
            //             weapons: {
            //                   primary: weapons.axe,
            //                   secondary: null,
            //                   concealed: null,
            //                   shield: null,
            //             } as IWeapons,
            //             loot: [
            //                   potions.largeHealthBuff,
            //                   potions.smallDamageBuff,
            //             ],
            //             imageFileName: "",
            //             startingLocation: "c2",
            //       },
            //       startingPositionY: "c",
            //       startingPositionX: 2,
            // },
            {
                  type: ElementClass.enemy,
                  elementProperties: {
                        id: "28be7086-bafe-49f5-9e3c-ec3ca90e45a6",
                        asleep: true,
                        angry: false,
                        level: 1,
                        maxHp: 50,
                        lowHealthThreshold: 6,
                        maxPauseDuration: 1,
                        name: "Test",
                        class: MonsterClass.Human,
                        startingDirection: Direction.S,
                        direction: Direction.S,
                        patrolArea: true,
                        directionsForPatrol: [
                        ],
                        startingTargetLocation: "g5",
                        maxHuntingDuration: 3,
                        startingState: CharacterState.walkingPath,
                        speechResponse: "I'm gonna kill you",
                        sleepResponse: "Zzzzzzzzzzzzzzzz",
                        lootParameters: {
                              level: 6,
                              allowWeapon: true,
                              allowPotion: false,
                              allowKey: false,
                        },
                        armour: {
                              head: armour.leatherHelmet,
                              arms: null,
                              hands: null,
                              torso: armour.leatherChestPiece,
                              legs: null,
                              boots: armour.leatherBoots,
                        },
                        weapons: {
                              primary: weapons.axe,
                              secondary: null,
                              concealed: null,
                              shield: null,
                        } as IWeapons,
                        loot: [
                              potions.largeHealthBuff,
                              potions.smallDamageBuff,
                        ],
                        imageFileName: "",
                        startingLocation: "c3",
                  },
                  startingPositionY: "c",
                  startingPositionX: 3,
            },
            // {
            //       type: ElementClass.enemy,
            //       elementProperties: {
            //             id: "28be7086-bafe-49f5-9e3c-ec3ca90e45a6",
            //             asleep: true,
            //             angry: false,
            //             level: 1,
            //             maxHp: 50,
            //             lowHealthThreshold: 6,
            //             maxPauseDuration: 1,
            //             name: "Test",
            //             class: MonsterClass.Human,
            //             startingDirection: Direction.S,
            //             direction: Direction.S,
            //             patrolArea: true,
            //             directionsForPatrol: [
            //             ],
            //             startingTargetLocation: "g4",
            //             maxHuntingDuration: 3,
            //             startingState: CharacterState.walkingPath,
            //             speechResponse: "I'm gonna kill you",
            //             sleepResponse: "Zzzzzzzzzzzzzzzz",
            //             lootParameters: {
            //                   level: 6,
            //                   allowWeapon: true,
            //                   allowPotion: false,
            //                   allowKey: false,
            //             },
            //             armour: {
            //                   head: armour.leatherHelmet,
            //                   arms: null,
            //                   hands: null,
            //                   torso: armour.leatherChestPiece,
            //                   legs: null,
            //                   boots: armour.leatherBoots,
            //             },
            //             weapons: {
            //                   primary: weapons.axe,
            //                   secondary: null,
            //                   concealed: null,
            //                   shield: null,
            //             } as IWeapons,
            //             loot: [
            //                   potions.largeHealthBuff,
            //                   potions.smallDamageBuff,
            //             ],
            //             imageFileName: "",
            //             startingLocation: "c4",
            //       },
            //       startingPositionY: "c",
            //       startingPositionX: 4,
            // },
            {
                  type: ElementClass.enemy,
                  elementProperties: {
                        id: "28be7086-bafe-49f5-9e3c-ec3ca90e45a6",
                        asleep: true,
                        angry: false,
                        level: 1,
                        maxHp: 50,
                        lowHealthThreshold: 6,
                        maxPauseDuration: 1,
                        name: "Test",
                        class: MonsterClass.Human,
                        startingDirection: Direction.S,
                        direction: Direction.S,
                        patrolArea: true,
                        directionsForPatrol: [
                        ],
                        startingTargetLocation: "g3",
                        maxHuntingDuration: 3,
                        startingState: CharacterState.walkingPath,
                        speechResponse: "I'm gonna kill you",
                        sleepResponse: "Zzzzzzzzzzzzzzzz",
                        lootParameters: {
                              level: 6,
                              allowWeapon: true,
                              allowPotion: false,
                              allowKey: false,
                        },
                        armour: {
                              head: armour.leatherHelmet,
                              arms: null,
                              hands: null,
                              torso: armour.leatherChestPiece,
                              legs: null,
                              boots: armour.leatherBoots,
                        },
                        weapons: {
                              primary: weapons.axe,
                              secondary: null,
                              concealed: null,
                              shield: null,
                        } as IWeapons,
                        loot: [
                              potions.largeHealthBuff,
                              potions.smallDamageBuff,
                        ],
                        imageFileName: "",
                        startingLocation: "c5",
                  },
                  startingPositionY: "c",
                  startingPositionX: 5,
            },
            // {
            //       type: ElementClass.enemy,
            //       elementProperties: {
            //             id: "28be7086-bafe-49f5-9e3c-ec3ca90e45a6",
            //             asleep: true,
            //             angry: false,
            //             level: 1,
            //             maxHp: 50,
            //             lowHealthThreshold: 6,
            //             maxPauseDuration: 1,
            //             name: "Test",
            //             class: MonsterClass.Human,
            //             startingDirection: Direction.S,
            //             direction: Direction.S,
            //             patrolArea: true,
            //             directionsForPatrol: [
            //             ],
            //             startingTargetLocation: "g2",
            //             maxHuntingDuration: 3,
            //             startingState: CharacterState.walkingPath,
            //             speechResponse: "I'm gonna kill you",
            //             sleepResponse: "Zzzzzzzzzzzzzzzz",
            //             lootParameters: {
            //                   level: 6,
            //                   allowWeapon: true,
            //                   allowPotion: false,
            //                   allowKey: false,
            //             },
            //             armour: {
            //                   head: armour.leatherHelmet,
            //                   arms: null,
            //                   hands: null,
            //                   torso: armour.leatherChestPiece,
            //                   legs: null,
            //                   boots: armour.leatherBoots,
            //             },
            //             weapons: {
            //                   primary: weapons.axe,
            //                   secondary: null,
            //                   concealed: null,
            //                   shield: null,
            //             } as IWeapons,
            //             loot: [
            //                   potions.largeHealthBuff,
            //                   potions.smallDamageBuff,
            //             ],
            //             imageFileName: "",
            //             startingLocation: "c6",
            //       },
            //       startingPositionY: "c",
            //       startingPositionX: 6,
            // },
            {
                  type: ElementClass.enemy,
                  elementProperties: {
                        id: "28be7086-bafe-49f5-9e3c-ec3ca90e45a6",
                        asleep: true,
                        angry: false,
                        level: 1,
                        maxHp: 50,
                        lowHealthThreshold: 6,
                        maxPauseDuration: 1,
                        name: "Test",
                        class: MonsterClass.Human,
                        startingDirection: Direction.S,
                        direction: Direction.S,
                        patrolArea: true,
                        directionsForPatrol: [
                        ],
                        startingTargetLocation: "g1",
                        maxHuntingDuration: 3,
                        startingState: CharacterState.walkingPath,
                        speechResponse: "I'm gonna kill you",
                        sleepResponse: "Zzzzzzzzzzzzzzzz",
                        lootParameters: {
                              level: 6,
                              allowWeapon: true,
                              allowPotion: false,
                              allowKey: false,
                        },
                        armour: {
                              head: armour.leatherHelmet,
                              arms: null,
                              hands: null,
                              torso: armour.leatherChestPiece,
                              legs: null,
                              boots: armour.leatherBoots,
                        },
                        weapons: {
                              primary: weapons.axe,
                              secondary: null,
                              concealed: null,
                              shield: null,
                        } as IWeapons,
                        loot: [
                              potions.largeHealthBuff,
                              potions.smallDamageBuff,
                        ],
                        imageFileName: "",
                        startingLocation: "c7",
                  },
                  startingPositionY: "c",
                  startingPositionX: 7,
            },
            // {
            //       type: ElementClass.enemy,
            //       elementProperties: {
            //             id: "28be7086-bafe-49f5-9e3c-ec3ca90e45a6",
            //             asleep: true,
            //             angry: false,
            //             level: 1,
            //             maxHp: 50,
            //             lowHealthThreshold: 6,
            //             maxPauseDuration: 1,
            //             name: "Test",
            //             class: MonsterClass.Human,
            //             startingDirection: Direction.S,
            //             direction: Direction.S,
            //             patrolArea: true,
            //             directionsForPatrol: [
            //             ],
            //             startingTargetLocation: "c1",
            //             maxHuntingDuration: 3,
            //             startingState: CharacterState.walkingPath,
            //             speechResponse: "I'm gonna kill you",
            //             sleepResponse: "Zzzzzzzzzzzzzzzz",
            //             lootParameters: {
            //                   level: 6,
            //                   allowWeapon: true,
            //                   allowPotion: false,
            //                   allowKey: false,
            //             },
            //             armour: {
            //                   head: armour.leatherHelmet,
            //                   arms: null,
            //                   hands: null,
            //                   torso: armour.leatherChestPiece,
            //                   legs: null,
            //                   boots: armour.leatherBoots,
            //             },
            //             weapons: {
            //                   primary: weapons.axe,
            //                   secondary: null,
            //                   concealed: null,
            //                   shield: null,
            //             } as IWeapons,
            //             loot: [
            //                   potions.largeHealthBuff,
            //                   potions.smallDamageBuff,
            //             ],
            //             imageFileName: "",
            //             startingLocation: "f1",
            //       },
            //       startingPositionY: "f",
            //       startingPositionX: 1,
            // },
            // {
            //       type: ElementClass.enemy,
            //       elementProperties: {
            //             id: "28be7086-bafe-49f5-9e3c-ec3ca90e45a6",
            //             asleep: true,
            //             angry: false,
            //             level: 1,
            //             maxHp: 50,
            //             lowHealthThreshold: 6,
            //             maxPauseDuration: 1,
            //             name: "Test",
            //             class: MonsterClass.Human,
            //             startingDirection: Direction.S,
            //             direction: Direction.S,
            //             patrolArea: true,
            //             directionsForPatrol: [
            //             ],
            //             startingTargetLocation: "a1",
            //             maxHuntingDuration: 3,
            //             startingState: CharacterState.walkingPath,
            //             speechResponse: "I'm gonna kill you",
            //             sleepResponse: "Zzzzzzzzzzzzzzzz",
            //             lootParameters: {
            //                   level: 6,
            //                   allowWeapon: true,
            //                   allowPotion: false,
            //                   allowKey: false,
            //             },
            //             armour: {
            //                   head: armour.leatherHelmet,
            //                   arms: null,
            //                   hands: null,
            //                   torso: armour.leatherChestPiece,
            //                   legs: null,
            //                   boots: armour.leatherBoots,
            //             },
            //             weapons: {
            //                   primary: weapons.axe,
            //                   secondary: null,
            //                   concealed: null,
            //                   shield: null,
            //             } as IWeapons,
            //             loot: [
            //                   potions.largeHealthBuff,
            //                   potions.smallDamageBuff,
            //             ],
            //             imageFileName: "",
            //             startingLocation: "f2",
            //       },
            //       startingPositionY: "f",
            //       startingPositionX: 2,
            // },
            // {
            //       type: ElementClass.enemy,
            //       elementProperties: {
            //             id: "28be7086-bafe-49f5-9e3c-ec3ca90e45a6",
            //             asleep: true,
            //             angry: false,
            //             level: 1,
            //             maxHp: 50,
            //             lowHealthThreshold: 6,
            //             maxPauseDuration: 1,
            //             name: "Test",
            //             class: MonsterClass.Human,
            //             startingDirection: Direction.S,
            //             direction: Direction.S,
            //             patrolArea: true,
            //             directionsForPatrol: [
            //             ],
            //             startingTargetLocation: "a1",
            //             maxHuntingDuration: 3,
            //             startingState: CharacterState.walkingPath,
            //             speechResponse: "I'm gonna kill you",
            //             sleepResponse: "Zzzzzzzzzzzzzzzz",
            //             lootParameters: {
            //                   level: 6,
            //                   allowWeapon: true,
            //                   allowPotion: false,
            //                   allowKey: false,
            //             },
            //             armour: {
            //                   head: armour.leatherHelmet,
            //                   arms: null,
            //                   hands: null,
            //                   torso: armour.leatherChestPiece,
            //                   legs: null,
            //                   boots: armour.leatherBoots,
            //             },
            //             weapons: {
            //                   primary: weapons.axe,
            //                   secondary: null,
            //                   concealed: null,
            //                   shield: null,
            //             } as IWeapons,
            //             loot: [
            //                   potions.largeHealthBuff,
            //                   potions.smallDamageBuff,
            //             ],
            //             imageFileName: "",
            //             startingLocation: "f3",
            //       },
            //       startingPositionY: "f",
            //       startingPositionX: 3,
            // },
            {
                  type: ElementClass.object,
                  elementProperties: {
                        name: "Old chest",
                        objectType: ObjectType.lootObject,
                        startingDirection: Direction.E,
                        direction: Direction.E,
                        canBeTraversed: false,
                        isInteractive: true,
                        itemReferenceNeeded: "b27f504c-4fb4-4855-a4e7-9facbf693c76",
                        imageFileName: "old-chest.png",
                        loot: [
                              potions.smallDamageBuff,
                        ]
                  },
                  startingPositionY: "b",
                  startingPositionX: 4,
            },
            {
                  type: ElementClass.object,
                  elementProperties: {
                        name: "Old chest",
                        objectType: ObjectType.lootObject,
                        startingDirection: Direction.E,
                        direction: Direction.E,
                        canBeTraversed: false,
                        isInteractive: true,
                        itemReferenceNeeded: "b27f504c-4fb4-4855-a4e7-9facbf693c76",
                        imageFileName: "old-chest.png",
                        loot: [
                              potions.smallDamageBuff,
                        ]
                  },
                  startingPositionY: "b",
                  startingPositionX: 3,
            },
            {
                  type: ElementClass.object,
                  elementProperties: {
                        name: "Old chest",
                        objectType: ObjectType.lootObject,
                        startingDirection: Direction.E,
                        direction: Direction.E,
                        canBeTraversed: false,
                        isInteractive: true,
                        itemReferenceNeeded: "b27f504c-4fb4-4855-a4e7-9facbf693c76",
                        imageFileName: "old-chest.png",
                        loot: [
                              potions.smallDamageBuff,
                        ]
                  },
                  startingPositionY: "b",
                  startingPositionX: 5,
            },
      ] as IAreaElement[],
      areaCompleteRequirements: {
            item: false,
            monster: true
      }
};
