import { IAreaElement } from "../../game/area/interfaces";
import { IWeaponSlots } from "../../game/item/interfaces";
import { CharacterState, Direction, ElementClass, ObjectType } from "../../game/shared/enums";
import { armour, keyItems, potions, weapons } from "../items";
import { player } from "../characters";
import { BackgroundMusic } from "../../shared/enums";

export default {
    room: 6,
    backgroundMusic: BackgroundMusic.bossMusic,
    floorImageFileName: "pavement.png",
    areaVisited: false,
    areaLoadMessage: "Test area",
    areaElements: [
        player,
        {
            type: ElementClass.npc,
            elementProperties: {
                id: "9b385219-a8df-47f9-b7ce-000d1bb18a9d",
                maxHp: 50,
                baseDamage: 2,
                lowHealthThreshold: 6,
                attackPauseDuration: 1,
                name: "Test",
                startingDirection: Direction.S,
                directionsForPatrol: [
                ],
                startingTargetLocation: "c7",
                maxHuntingDuration: 3,
                startingState: CharacterState.walkingPath,
                speechResponse: "I'm gonna kill you",
                sleepResponse: "Zzzzzzzzzzzzzzzz",
                armour: {
                    head: armour.leatherHelmet,
                    arms: null,
                    hands: null,
                    torso: armour.leatherChestPiece,
                    legs: null,
                    boots: armour.leatherBoots,
                },
                weapons: {
                    primary: weapons.axe,
                } as IWeaponSlots,
                loot: [
                    potions.largeHealthBuff,
                    potions.smallDamageBuff,
                ],
                imageFileName: "shadow-npc.png",
                startingLocation: "g1",
            },
            startingPositionY: "g",
            startingPositionX: 1,
        },
        {
            type: ElementClass.npc,
            elementProperties: {
                id: "92b039ed-f3a0-4c9a-803a-44d9bca0252c",
                maxHp: 50,
                baseDamage: 2,
                lowHealthThreshold: 6,
                attackPauseDuration: 1,
                name: "Test",
                startingDirection: Direction.S,
                directionsForPatrol: [
                ],
                startingTargetLocation: "c6",
                maxHuntingDuration: 3,
                startingState: CharacterState.walkingPath,
                speechResponse: "I'm gonna kill you",
                sleepResponse: "Zzzzzzzzzzzzzzzz",
                armour: {
                    head: armour.leatherHelmet,
                    arms: null,
                    hands: null,
                    torso: armour.leatherChestPiece,
                    legs: null,
                    boots: armour.leatherBoots,
                },
                weapons: {
                    primary: weapons.axe,
                } as IWeaponSlots,
                loot: [
                    potions.largeHealthBuff,
                    potions.smallDamageBuff,
                ],
                imageFileName: "shadow-npc.png",
                startingLocation: "g2",
            },
            startingPositionY: "g",
            startingPositionX: 2,
        },
        {
            type: ElementClass.npc,
            elementProperties: {
                id: "c67a81c0-ae3b-4f6f-8c60-b8f5df5d44f9",
                maxHp: 50,
                baseDamage: 2,
                lowHealthThreshold: 6,
                attackPauseDuration: 1,
                name: "Test",
                startingDirection: Direction.S,
                directionsForPatrol: [
                ],
                startingTargetLocation: "c4",
                maxHuntingDuration: 3,
                startingState: CharacterState.walkingPath,
                speechResponse: "I'm gonna kill you",
                sleepResponse: "Zzzzzzzzzzzzzzzz",
                armour: {
                    head: armour.leatherHelmet,
                    arms: null,
                    hands: null,
                    torso: armour.leatherChestPiece,
                    legs: null,
                    boots: armour.leatherBoots,
                },
                weapons: {
                    primary: weapons.axe,
                } as IWeaponSlots,
                loot: [
                    potions.largeHealthBuff,
                    potions.smallDamageBuff,
                ],
                imageFileName: "shadow-npc.png",
                startingLocation: "g4",
            },
            startingPositionY: "g",
            startingPositionX: 4,
        },
        {
            type: ElementClass.npc,
            elementProperties: {
                id: "ab302ef2-573d-45b1-93ad-e5c929b2e891",
                maxHp: 50,
                baseDamage: 2,
                lowHealthThreshold: 6,
                attackPauseDuration: 1,
                name: "Test",
                startingDirection: Direction.S,
                directionsForPatrol: [
                ],
                startingTargetLocation: "c2",
                maxHuntingDuration: 3,
                startingState: CharacterState.walkingPath,
                speechResponse: "I'm gonna kill you",
                sleepResponse: "Zzzzzzzzzzzzzzzz",
                armour: {
                    head: armour.leatherHelmet,
                    arms: null,
                    hands: null,
                    torso: armour.leatherChestPiece,
                    legs: null,
                    boots: armour.leatherBoots,
                },
                weapons: {
                    primary: weapons.axe,
                } as IWeaponSlots,
                loot: [
                    potions.largeHealthBuff,
                    potions.smallDamageBuff,
                ],
                imageFileName: "shadow-npc.png",
                startingLocation: "g6",
            },
            startingPositionY: "g",
            startingPositionX: 6,
        },
        {
            type: ElementClass.npc,
            elementProperties: {
                id: "daf46483-58a5-4154-91c5-fc569e5f6a6b",
                maxHp: 50,
                baseDamage: 2,
                lowHealthThreshold: 6,
                attackPauseDuration: 1,
                name: "Test",
                startingDirection: Direction.S,
                directionsForPatrol: [
                ],
                startingTargetLocation: "c1",
                maxHuntingDuration: 3,
                startingState: CharacterState.walkingPath,
                speechResponse: "I'm gonna kill you",
                sleepResponse: "Zzzzzzzzzzzzzzzz",
                armour: {
                    head: armour.leatherHelmet,
                    arms: null,
                    hands: null,
                    torso: armour.leatherChestPiece,
                    legs: null,
                    boots: armour.leatherBoots,
                },
                weapons: {
                    primary: weapons.axe,
                } as IWeaponSlots,
                loot: [
                    potions.largeHealthBuff,
                    potions.smallDamageBuff,
                ],
                imageFileName: "shadow-npc.png",
                startingLocation: "g7",
            },
            startingPositionY: "g",
            startingPositionX: 7,
        },
        {
            type: ElementClass.enemy,
            elementProperties: {
                id: "53831a37-395e-47f6-88ed-bc6be994c0c6",
                maxHp: 50,
                baseDamage: 2,
                lowHealthThreshold: 6,
                attackPauseDuration: 1,
                name: "Test",
                startingDirection: Direction.S,
                directionsForPatrol: [
                ],
                startingTargetLocation: "g7",
                maxHuntingDuration: 3,
                startingState: CharacterState.walkingPath,
                speechResponse: "I'm gonna kill you",
                sleepResponse: "Zzzzzzzzzzzzzzzz",
                armour: {
                    head: armour.leatherHelmet,
                    arms: null,
                    hands: null,
                    torso: armour.leatherChestPiece,
                    legs: null,
                    boots: armour.leatherBoots,
                },
                weapons: {
                    primary: weapons.axe,
                } as IWeaponSlots,
                loot: [
                    potions.largeHealthBuff,
                    potions.smallDamageBuff,
                ],
                imageFileName: "shadow-enemy.png",
                startingLocation: "c1",
            },
            startingPositionY: "c",
            startingPositionX: 1,
        },
        {
            type: ElementClass.enemy,
            elementProperties: {
                id: "5ac92002-3033-4adb-9832-3a520ea02f5f",
                maxHp: 50,
                baseDamage: 2,
                lowHealthThreshold: 6,
                attackPauseDuration: 1,
                name: "Test",
                startingDirection: Direction.S,
                directionsForPatrol: [
                ],
                startingTargetLocation: "g5",
                maxHuntingDuration: 3,
                startingState: CharacterState.walkingPath,
                speechResponse: "I'm gonna kill you",
                sleepResponse: "Zzzzzzzzzzzzzzzz",
                armour: {
                    head: armour.leatherHelmet,
                    arms: null,
                    hands: null,
                    torso: armour.leatherChestPiece,
                    legs: null,
                    boots: armour.leatherBoots,
                },
                weapons: {
                    primary: weapons.axe,
                } as IWeaponSlots,
                loot: [
                    potions.largeHealthBuff,
                    potions.smallDamageBuff,
                    keyItems.lightBulb
                ],
                imageFileName: "shadow-enemy.png",
                startingLocation: "c3",
            },
            startingPositionY: "c",
            startingPositionX: 3,
        },
        {
            type: ElementClass.enemy,
            elementProperties: {
                id: "2b475c48-65a6-4d5e-8908-ddd2593457f5",
                maxHp: 50,
                baseDamage: 2,
                lowHealthThreshold: 6,
                attackPauseDuration: 1,
                name: "Test",
                startingDirection: Direction.S,
                directionsForPatrol: [
                ],
                startingTargetLocation: "g3",
                maxHuntingDuration: 3,
                startingState: CharacterState.walkingPath,
                speechResponse: "I'm gonna kill you",
                sleepResponse: "Zzzzzzzzzzzzzzzz",
                armour: {
                    head: armour.leatherHelmet,
                    arms: null,
                    hands: null,
                    torso: armour.leatherChestPiece,
                    legs: null,
                    boots: armour.leatherBoots,
                },
                weapons: {
                    primary: weapons.axe,
                } as IWeaponSlots,
                loot: [
                    potions.largeHealthBuff,
                    potions.smallDamageBuff,
                ],
                imageFileName: "shadow-enemy.png",
                startingLocation: "c5",
            },
            startingPositionY: "c",
            startingPositionX: 5,
        },
        {
            type: ElementClass.enemy,
            elementProperties: {
                id: "595f3d40-37df-4531-b4b3-35bf2ede1f2f",
                maxHp: 50,
                baseDamage: 2,
                lowHealthThreshold: 6,
                attackPauseDuration: 1,
                name: "Test",
                startingDirection: Direction.S,
                directionsForPatrol: [
                ],
                startingTargetLocation: "g1",
                maxHuntingDuration: 3,
                startingState: CharacterState.walkingPath,
                speechResponse: "I'm gonna kill you",
                sleepResponse: "Zzzzzzzzzzzzzzzz",
                armour: {
                    head: armour.leatherHelmet,
                    arms: null,
                    hands: null,
                    torso: armour.leatherChestPiece,
                    legs: null,
                    boots: armour.leatherBoots,
                },
                weapons: {
                    primary: weapons.axe,
                } as IWeaponSlots,
                loot: [
                    potions.largeHealthBuff,
                    potions.smallDamageBuff,
                ],
                imageFileName: "shadow-enemy.png",
                startingLocation: "c7",
            },
            startingPositionY: "c",
            startingPositionX: 7,
        },
        {
            type: ElementClass.object,
            elementProperties: {
                name: "Old chest",
                objectType: ObjectType.lootObject,
                startingDirection: Direction.E,
                isInteractive: true,
                isLocked: true,
                itemReferenceNeeded: "b27f504c-4fb4-4855-a4e7-9facbf693c76",
                imageFileName: "old-chest.png",
                soundEffect: "openChest",
                loot: [
                    keyItems.trophy,
                ]
            },
            startingPositionY: "d",
            startingPositionX: 4,
        },
        {
            type: ElementClass.object,
            elementProperties: {
                name: "Old chest",
                objectType: ObjectType.lootObject,
                startingDirection: Direction.E,
                isInteractive: true,
                isLocked: true,
                itemReferenceNeeded: "b27f504c-4fb4-4855-a4e7-9facbf693c76",
                imageFileName: "old-chest.png",
                soundEffect: "openChest",
                loot: [
                    keyItems.trophy,
                ]
            },
            startingPositionY: "a",
            startingPositionX: 3,
        },
    ] as IAreaElement[]
};
